### ISSUE TITLE
issue installing on Linux 

### ISSUE THREAD

**Issue by momonala** [QuantStack/xeus-cling#100]
Hi, after the creating a new environment, I get this error on the first Conda install for Linux (latest version of Ubuntu). I installed on Ubuntu several months ago and it installed fine, but this is a new issue. Let me know if there is a solution. Thanks!

``` 
openssl 1.0.2l: ############################################################################# | 100% 
Preparing transaction: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 743, in __call__
        return func(*args, **kwargs)
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 76, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 11, in execute
        install(args, parser, 'install')
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 255, in install
        handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 285, in handle_txn
        unlink_link_transaction.execute()
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 220, in execute
        self.verify()
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/common/io.py", line 415, in decorated
        return f(*args, **kwds)
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 197, in verify
        self.prepare()
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 189, in prepare
        stp.remove_specs, stp.update_specs)
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 253, in _prepare
        for prec, pcrec in zip(link_precs, pkg_cache_recs_to_link))
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 253, in <genexpr>
        for prec, pcrec in zip(link_precs, pkg_cache_recs_to_link))
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 92, in read_package_info
        index_json_record = read_index_json(epd)
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 112, in read_index_json
        record = IndexJsonRecord(**json.load(fi))
      File "/home/mohit/miniconda3/lib/python3.6/json/__init__.py", line 299, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "/home/mohit/miniconda3/lib/python3.6/json/__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "/home/mohit/miniconda3/lib/python3.6/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/mohit/miniconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ /home/mohit/miniconda3/bin/conda install cling -c QuantStack -c conda-forge`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=cling
             CONDA_PREFIX=/home/mohit/miniconda3/envs/cling
    CONDA_PROMPT_MODIFIER=(cling)
         CONDA_PYTHON_EXE=/home/mohit/miniconda3/bin/python
               CONDA_ROOT=/home/mohit/miniconda3
              CONDA_SHLVL=1
                     PATH=/home/mohit/miniconda3/envs/cling/bin:/home/mohit/miniconda3/bin:/usr/
                          local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/us
                          r/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : cling
    active env location : /home/mohit/miniconda3/envs/cling
            shell level : 1
       user config file : /home/mohit/.condarc
 populated config files : 
          conda version : 4.4.7
    conda-build version : not installed
         python version : 3.6.3.final.0
       base environment : /home/mohit/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/QuantStack/linux-64
                          https://conda.anaconda.org/QuantStack/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/mohit/miniconda3/pkgs
                          /home/mohit/.conda/pkgs
       envs directories : /home/mohit/miniconda3/envs
                          /home/mohit/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/3.6.3 Linux/4.13.0-25-generic ubuntu/17.10 glibc/2.26
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

**Comment by gouarin** [comment]
How did you get the first error with openssl?

Le 18 janv. 2018 4:42 PM, "Mohit Nalavadi" <notifications@github.com> a
écrit :

**Comment by momonala** [comment]
I believe that openssl bit was from the downloading and extraction of the packages.  Here is the full error report if that is helpful 

```
(cling) mohit@mohit-VirtualBox:~/xeus-cling$ conda install cling -c QuantStack -c conda-forge
Solving environment: done

## Package Plan ##

  environment location: /home/mohit/miniconda3/envs/cling

  added / updated specs: 
    - cling


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2017.11.5  |                0         145 KB  QuantStack
    certifi-2017.7.27.1        |           py36_0         204 KB  QuantStack
    openssl-1.0.2l             |                0         3.5 MB  QuantStack
    ------------------------------------------------------------
                                           Total:         3.9 MB

The following NEW packages will be INSTALLED:

    clangdev:        3.9.1-cling_5     QuantStack  [cling]
    cling:           0.3.post2-cling_4 QuantStack  [cling]
    cling-patches:   1-0               QuantStack 
    gcc-6:           6.1.0-0           QuantStack 
    icu:             58.1-1            QuantStack 
    isl:             0.16.1-0          QuantStack 
    libcxx:          3.9.1-0           QuantStack 
    libgcc-6:        6.2.0-2           QuantStack 
    libiconv:        1.14-4            QuantStack 
    libxml2:         2.9.4-4           QuantStack 
    llvmdev:         3.9.1-cling_5     QuantStack  [cling]
    mpc:             1.0.3-4           QuantStack 
    mpfr:            3.1.5-0           QuantStack 
    system:          5.8-2             QuantStack 

The following packages will be UPDATED:

    ca-certificates: 2017.11.5-0       conda-forge --> 2017.11.5-0        QuantStack

The following packages will be DOWNGRADED:

    certifi:         2017.11.5-py36_0  conda-forge --> 2017.7.27.1-py36_0 QuantStack
    openssl:         1.0.2n-0          conda-forge --> 1.0.2l-0           QuantStack

Proceed ([y]/n)? y


Downloading and Extracting Packages
ca-certificates 2017.11.5: ################################################################## | 100% 
certifi 2017.7.27.1: ######################################################################## | 100% 
openssl 1.0.2l: ############################################################################# | 100% 
Preparing transaction: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 743, in __call__
        return func(*args, **kwargs)
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 76, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 11, in execute
        install(args, parser, 'install')
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 255, in install
        handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 285, in handle_txn
        unlink_link_transaction.execute()
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 220, in execute
        self.verify()
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/common/io.py", line 415, in decorated
        return f(*args, **kwds)
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 197, in verify
        self.prepare()
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 189, in prepare
        stp.remove_specs, stp.update_specs)
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 253, in _prepare
        for prec, pcrec in zip(link_precs, pkg_cache_recs_to_link))
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 253, in <genexpr>
        for prec, pcrec in zip(link_precs, pkg_cache_recs_to_link))
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 92, in read_package_info
        index_json_record = read_index_json(epd)
      File "/home/mohit/miniconda3/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 112, in read_index_json
        record = IndexJsonRecord(**json.load(fi))
      File "/home/mohit/miniconda3/lib/python3.6/json/__init__.py", line 299, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "/home/mohit/miniconda3/lib/python3.6/json/__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "/home/mohit/miniconda3/lib/python3.6/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/mohit/miniconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ /home/mohit/miniconda3/bin/conda install cling -c QuantStack -c conda-forge`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=cling
             CONDA_PREFIX=/home/mohit/miniconda3/envs/cling
    CONDA_PROMPT_MODIFIER=(cling)
         CONDA_PYTHON_EXE=/home/mohit/miniconda3/bin/python
               CONDA_ROOT=/home/mohit/miniconda3
              CONDA_SHLVL=1
                     PATH=/home/mohit/miniconda3/envs/cling/bin:/home/mohit/miniconda3/bin:/usr/
                          local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/us
                          r/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : cling
    active env location : /home/mohit/miniconda3/envs/cling
            shell level : 1
       user config file : /home/mohit/.condarc
 populated config files : 
          conda version : 4.4.7
    conda-build version : not installed
         python version : 3.6.3.final.0
       base environment : /home/mohit/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/QuantStack/linux-64
                          https://conda.anaconda.org/QuantStack/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/mohit/miniconda3/pkgs
                          /home/mohit/.conda/pkgs
       envs directories : /home/mohit/miniconda3/envs
                          /home/mohit/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/3.6.3 Linux/4.13.0-25-generic ubuntu/17.10 glibc/2.26
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: 
No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

(cling) mohit@mohit-VirtualBox:~/xeus-cling$ ^C


```

**Comment by momonala** [comment]
Hi, just saw your suggestion and tried it. I no longer get the previous error and all libraries downloaded and installed. However, now I get the following import error when running `jupyter notebook`. 

```
(cling) mohit@mohit-VirtualBox:~$ jupyter notebook
Traceback (most recent call last):
  File "/home/mohit/miniconda3/envs/cling/bin/jupyter-notebook", line 4, in <module>
    import notebook.notebookapp
  File "/home/mohit/miniconda3/envs/cling/lib/python3.6/site-packages/notebook/notebookapp.py", line 39, in <module>
    from zmq.eventloop import ioloop
  File "/home/mohit/miniconda3/envs/cling/lib/python3.6/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/home/mohit/miniconda3/envs/cling/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/mohit/miniconda3/envs/cling/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/mohit/miniconda3/envs/cling/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/mohit/miniconda3/envs/cling/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/mohit/miniconda3/envs/cling/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libzmq.so.5.1.1: cannot open shared object file: No such file or directory
(cling) mohit@mohit-VirtualBox:~$
```

**Comment by gouarin** [comment]
We are moving all the packages from my channel to QuantStack channel and this issue will be fixed. 

For now, you can add a symbolic link to have this issue solved.

```
ln -s /home/mohit/miniconda3/envs/cling/lib/libzmq.so.5.1.3.so /home/mohit/miniconda3/envs/cling/lib/libzmq.so.5.1.1.so
```

**Comment by momonala** [comment]
Great. I removed the environment and did a clean install for zeus-cling and everything installed correctly. Thanks!
