### ISSUE TITLE
xeus-cling executable crashes with infinite recursion

### ISSUE THREAD

**Issue by yurivict** [QuantStack/xeus-cling#184]
It is called with the arguments ```-f /tmp/kernel-830b7892-add2-4498-ab47-5eef581993e3.json -std=c++14```.

```
(gdb) r -f /tmp/kernel-830b7892-add2-4498-ab47-5eef581993e3.json -std=c++14
Starting program: /usr/local/bin/xeus-cling.shadow -f /tmp/kernel-830b7892-add2-4498-ab47-5eef581993e3.json -std=c++14

Program received signal SIGSEGV, Segmentation fault.
0x0000000801089927 in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
(gdb) bt
#0  0x0000000801089927 in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
#1  0x00000008024df316 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::CreateUpdateSpace(unsigned long&) () from /usr/local/lib/libcryptopp.so.7
#2  0x000000080108992a in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
#3  0x00000008024df316 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::CreateUpdateSpace(unsigned long&) () from /usr/local/lib/libcryptopp.so.7
#4  0x000000080108992a in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
#5  0x00000008024df316 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::CreateUpdateSpace(unsigned long&) () from /usr/local/lib/libcryptopp.so.7
#6  0x000000080108992a in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
#7  0x00000008024df316 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::CreateUpdateSpace(unsigned long&) () from /usr/local/lib/libcryptopp.so.7
#8  0x000000080108992a in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
#9  0x00000008024df316 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::CreateUpdateSpace(unsigned long&) () from /usr/local/lib/libcryptopp.so.7
#10 0x000000080108992a in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
#11 0x00000008024df316 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::CreateUpdateSpace(unsigned long&) () from /usr/local/lib/libcryptopp.so.7
#12 0x000000080108992a in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
#13 0x00000008024df316 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::CreateUpdateSpace(unsigned long&) () from /usr/local/lib/libcryptopp.so.7
#14 0x000000080108992a in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
#15 0x00000008024df316 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::CreateUpdateSpace(unsigned long&) () from /usr/local/lib/libcryptopp.so.7
#16 0x000000080108992a in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
#17 0x00000008024df316 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::CreateUpdateSpace(unsigned long&) () from /usr/local/lib/libcryptopp.so.7
#18 0x000000080108992a in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
#19 0x00000008024df316 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::CreateUpdateSpace(unsigned long&) () from /usr/local/lib/libcryptopp.so.7
#20 0x000000080108992a in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
#21 0x00000008024df316 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::CreateUpdateSpace(unsigned long&) () from /usr/local/lib/libcryptopp.so.7
#22 0x000000080108992a in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
#23 0x00000008024df316 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::CreateUpdateSpace(unsigned long&) () from /usr/local/lib/libcryptopp.so.7
#24 0x000000080108992a in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
#25 0x00000008024df316 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::CreateUpdateSpace(unsigned long&) () from /usr/local/lib/libcryptopp.so.7
#26 0x000000080108992a in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
#27 0x00000008024df316 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::CreateUpdateSpace(unsigned long&) () from /usr/local/lib/libcryptopp.so.7
#28 0x000000080108992a in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
#29 0x00000008024df316 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::CreateUpdateSpace(unsigned long&) () from /usr/local/lib/libcryptopp.so.7
#30 0x000000080108992a in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
#31 0x00000008024df316 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::CreateUpdateSpace(unsigned long&) () from /usr/local/lib/libcryptopp.so.7
#32 0x000000080108992a in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
#33 0x00000008024df316 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::CreateUpdateSpace(unsigned long&) () from /usr/local/lib/libcryptopp.so.7
#34 0x000000080108992a in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
#35 0x00000008024df316 in CryptoPP::IteratedHashBase<unsigned int, CryptoPP::HashTransformation>::CreateUpdateSpace(unsigned long&) () from /usr/local/lib/libcryptopp.so.7
#36 0x000000080108992a in CryptoPP::HashTransformation::Final(unsigned char*) () from /usr/local/lib/libxeus.so.1
```

```
$ cat /tmp/kernel-830b7892-add2-4498-ab47-5eef581993e3.json
{
  "stdin_port": 22603, 
  "ip": "127.0.0.1", 
  "control_port": 22604, 
  "hb_port": 22605, 
  "signature_scheme": "hmac-sha256", 
  "key": "dd0dd852-addf385ce0de4a17791cdd29", 
  "kernel_name": "xeus-cling-cpp14", 
  "shell_port": 22601, 
  "transport": "tcp", 
  "iopub_port": 22602
}
```

```cryptopp-7.0.0 ```

**Comment by yurivict** [comment]
Never mind. It was some ```cryptopp``` version mismatch.
