### ISSUE TITLE
[Rebuild] Cannot start c++ kernel

### ISSUE THREAD

**Issue by wiso** [QuantStack/xeus-cling#212]
I have installed xeus-cling as from the README:

```
conda create -n cling
conda activate cling
conda install xeus-cling notebook -c QuantStack -c conda-forge
```

which install several packages, including

```
    clangdev:          5.0.0-cling_1           QuantStack  [cling]
    gcc-7:             7.2.0-2                 QuantStack 
    xeus:              0.18.1-cling_0          QuantStack  [cling]
    jupyter_client:    5.2.4-py_0              conda-forge
    jupyter_core:      4.4.0-py_0              conda-forge
```

I am using fish shell (I tried also bash) on fedora 29. Conda is from the miniconda installer.

When starting a jupyter notebook:

    jupyter notebook

I get a bunch of errors, but probably not important:

```
[W 15:59:14.722 NotebookApp] server_extensions is deprecated, use nbserver_extensions
[W 15:59:14.985 NotebookApp] Error loading server extension ipyparallel.nbextension
    Traceback (most recent call last):
      File "/home/turra/.conda/envs/cling/lib/python3.6/site-packages/notebook/notebookapp.py", line 1572, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/home/turra/.conda/envs/cling/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'ipyparallel'
[W 15:59:14.987 NotebookApp] Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "/home/turra/.conda/envs/cling/lib/python3.6/site-packages/notebook/notebookapp.py", line 1572, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/home/turra/.conda/envs/cling/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
[I 15:59:14.987 NotebookApp] Serving notebooks from local directory: /home/turra
[I 15:59:14.987 NotebookApp] The Jupyter Notebook is running at:
[I 15:59:14.987 NotebookApp] http://localhost:8888/?token=a7a8c77228e25451588a6c1e691b9655fee87178f4545233
[I 15:59:14.987 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:59:14.995 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///run/user/1000/jupyter/nbserver-28790-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=a7a8c77228e25451588a6c1e691b9655fee87178f4545233
[28844:28844:1220/155915.477558:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-process.
È stata creata una nuova finestra nella sessione corrente del browser.
[W 15:59:17.274 NotebookApp] 404 GET /nbextensions/nbextensions_configurator/tree_tab/main.js?v=20181220155914 (::1) 10.71ms referer=http://localhost:8888/tree

```

Then when starting a new c++17 kernel:

```
[I 16:01:27.390 NotebookApp] Creating new notebook in 
[I 16:01:28.613 NotebookApp] Kernel started: a4596797-41de-46a5-9a33-edf494166d10
[W 16:01:28.658 NotebookApp] 404 GET /nbextensions/nbextensions_configurator/config_menu/main.js?v=20181220155914 (::1) 3.89ms referer=http://localhost:8888/notebooks/Untitled11.ipynb?kernel_name=xeus-cling-cpp17
[W 16:01:28.881 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20181220155914 (::1) 2.09ms referer=http://localhost:8888/notebooks/Untitled11.ipynb?kernel_name=xeus-cling-cpp17
[I 16:01:31.608 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
[I 16:01:34.627 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
[I 16:01:37.647 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
[I 16:01:40.657 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
[W 16:01:43.674 NotebookApp] KernelRestarter: restart failed
[W 16:01:43.675 NotebookApp] Kernel a4596797-41de-46a5-9a33-edf494166d10 died, removing from map.
[W 16:02:28.822 NotebookApp] Timeout waiting for kernel_info reply from a4596797-41de-46a5-9a33-edf494166d10
[E 16:02:28.830 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: a4596797-41de-46a5-9a33-edf494166d10)
```

**Comment by SylvainCorlay** [comment]
There seems to be an issue with the GCC package from the QuantStack channel on most recent versions of linux distributions.

We have been working on a rebuild of the xeus stack as part of the "conda-forge rebuild" endeavor which has been going on in the past few month. 

Basically, all packages of conda-forge are being migrated to the latest conda-build infrastructure that uses more modern compilers, and will allow for a continuous release process. The "progress bar" for the rebuild is available on https://conda-forge.org/status/:
![screenshot from 2018-12-22 13-55-51](https://user-images.githubusercontent.com/2397974/50374626-5a321680-05f1-11e9-8602-481f655b2103.png)

You should already be able to try out the new build for xeus-cling on the `conda-forge/label/gcc7` channel.

In a clean environment, `conda install xeus-cling notebook -c conda-forge/label/gcc7`. When the rebuild is complete, this will be come the official conda-forge channel. Let me know how this goes!

**Comment by wiso** [comment]
it works, thanks!

**Comment by SylvainCorlay** [comment]
Thanks, closing.

**Comment by avimehenwal** [comment]
Solution works on `archlinux 4.19.13-1-MANJARO` as well. Thanks :)

**Comment by satheeshxolo** [comment]
Works now on Ubuntu 18.04.2 LTS! Thanks!
