### ISSUE TITLE
problem running

### ISSUE THREAD

**Issue by hfarazi** [QuantStack/xeus-cling#79]
hafez@hafez-pc:~$ jupyter notebook
/home/hafez/anaconda3/compiler_compat/ld: cannot find -lpthread
/home/hafez/anaconda3/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/hafez/anaconda3/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 42, in <module>
    from zmq.eventloop import ioloop
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libzmq.so.5.1.2: cannot open shared object file: No such file or directory

**Comment by gouarin** [comment]
This is the same problem mentioned here #76

**Comment by SylvainCorlay** [comment]
@hfarazi this is a known issue:

- unfortunately cling requires a special build of libzmq, for binary compatibility reason. So all the dependencies must come from the QuantStack channel. Another version libzmq is already in the main anaconda distribution.

**The solution**:

you can get around this by either installing cling and the notebook in an empty clean environment, or by starting from an empty miniconda installation.

**Comment by hfarazi** [comment]
Ok how can I clean my current (root) environment?

**Comment by hfarazi** [comment]
Probably you should write in the README.md that people need to create a new env for this.

**Comment by SylvainCorlay** [comment]
Yes, we should probably emphasize on this.
