### ISSUE TITLE
jupyter notebook crashes on Linux Mint 18.2

### ISSUE THREAD

**Issue by rscircus** [QuantStack/xeus-cling#82]
Setup:

```
0> conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 2.7.14.final.0
       requests version : 2.18.4
       root environment : /home/username/local/share/ana2  (writable)
    default environment : /home/username/local/share/ana2
       envs directories : /home/username/local/share/ana2/envs
                          /home/username/.conda/envs
          package cache : /home/username/local/share/ana2/pkgs
                          /home/username/.conda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/linux-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/username/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/2.7.14 Linux/4.8.0-58-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

```

Error:
```
0> jupyter notebook
/home/username/local/share/ana2/compiler_compat/ld: cannot find -lpthread
/home/username/local/share/ana2/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/username/local/share/ana2/bin/jupyter-notebook", line 4, in <module>
    import notebook.notebookapp
  File "/home/username/local/share/ana2/lib/python2.7/site-packages/notebook/notebookapp.py", line 42, in <module>
    from zmq.eventloop import ioloop
  File "/home/username/local/share/ana2/lib/python2.7/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/home/username/local/share/ana2/lib/python2.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/username/local/share/ana2/lib/python2.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/username/local/share/ana2/lib/python2.7/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/username/local/share/ana2/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libzmq.so.5.1.2: cannot open shared object file: No such file or directory
```

This is a vanilla install. The only thing applied is:

```
> conda install cling -c QuantStack -c conda-forge
> conda install xeus-cling -c QuantStack -c conda-forge
> conda install notebook -c conda-forge
```

I already checked my `~/.zshrc` and removed `PYTHONPATH` and the customizations in `LD_LIBRARY_PATH`.

Further, there seems to be a similar issue with R: https://github.com/ContinuumIO/anaconda-issues/issues/506

And I'm not willing to link `libzmq` into `/lib` right now... Any ideas?

**Comment by gouarin** [comment]
This issue is also mentioned here #76. You will find the solution too.

I will update the readme !

**Comment by rscircus** [comment]
Solution referenced in #76:

```
conda create -n cling
source activate cling
conda install xeus-cling
```

**Comment by rscircus** [comment]
Nope, this wasn't it.

**Comment by rscircus** [comment]
I'll investigate further into @SylvainCorlay's [comment](https://github.com/QuantStack/xeus-cling/issues/74#issuecomment-343681758) in #74.

**Comment by gouarin** [comment]
Could you give us the output of

```
conda list
```

And the error message that you have ?

**Comment by rscircus** [comment]
The error message is listed above. It's exact, except that I replaced the user's name with a generic `username` on the specific machine. Furthermore I just `rm -rf ~/local/share/ana2` and start again with the current installation procedure, which resembles the line of thought in #74. Sorry. 😊 

I think, the key is:

> If you start from a regular anaconda installation (instead of a miniconda), it already has libzmq, built with a too old compiler but with the same package version number, and conda does not update it with a QuantStack build.
via @SylvainCorlay.

**Comment by gouarin** [comment]
Oh I see !!

**Comment by rscircus** [comment]
My suspicion is, that the problem is zeromq. Which in fact is not updated with QuantStack's very own version due to the version number match.

**Comment by rscircus** [comment]
I put a little more emphasis on this via https://github.com/QuantStack/xeus-cling/pull/83 😊 

Thanks for your work, guys.

**Comment by rscircus** [comment]
```
Package plan for installation in environment /home/rawland/local/share/miniconda2/envs/cling:

The following NEW packages will be INSTALLED:

    cppzmq:     4.2.1-0  QuantStack
    cryptopp:   5.6.5-3  QuantStack
    libsodium:  1.0.10-0 QuantStack
    util-linux: 2.21-0   QuantStack
    xeus:       0.8.0-0  QuantStack
    xeus-cling: 0.0.7-0  QuantStack
    xtl:        0.3.6-0  QuantStack
    zeromq:     4.2.1-1  QuantStack

Proceed ([y]/n)? 
```

Yes. Almost there. 😊

**Comment by rscircus** [comment]
Works like a charm, when following the [current installation procedure](https://github.com/QuantStack/xeus-cling#installation) in the README.md.

**Comment by gouarin** [comment]
Good to know.

Enjoy ;)

Le 30 nov. 2017 4:58 PM, "ʇɹǝqƃǝᴉs puɐloɹ" <notifications@github.com> a
écrit :
